[package]
name = "nicesigner"
version = "0.1.0"
edition = "2021"


[lib]
name = "nicesigner"
crate-type = ["cdylib"]


[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "abi3-py37"] }
sha256 = "1.5.0"
bitcoin = "0.32.4"
hex = "0.4"
secp256k1 = "0.29.0"
